# # WebRTC media server
---
{{- if eq .Values.mediaServer.deployment.enablement "enable"}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kms
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: kms
  replicas: {{ .Values.mediaServer.deployment.replicas}} # tells deployment to run 1 pods matching the template
  template: # create pods using pod definition in this template
    metadata:
      labels:
        app: kms
    spec:
      containers:
      - name: kms
        image: kurento/kurento-media-server:latest
        # image: kurento/kurento-media-server:6.7.1-xenial
        imagePullPolicy: {{ .Values.mediaServer.deployment.imagePullPolicy }}
        env:
          - name: "GST_DEBUG"
            # value: "Kurento*:5"
            # value: "5"
            # value: "3,sdp*:5,webrtc*:5,*dtls*:6"
            value: "4,*sdp*:6,*webrtc*:6,*endpoint*:6,agnosticbin:6,KurentoWebSocket*:6"
          - name: "KMS_ICE_TCP"
            value: "0"
          - name: "KMS_STUN_IP"
            value: ""
          - name: "KMS_STUN_PORT"
            value: ""
          - name: "KMS_TURN_URL"
            value: ""
          - name: "KMS_NETWORK_INTERFACES"
            value: "eth0"
          - name: "KMS_MIN_PORT"
            value: "10000"
          - name: "KMS_MAX_PORT"
            value: "20000"
          - name: "KMS_EXTERNAL_IPV4"
            value: ""
        ports:
        - containerPort: {{ .Values.mediaServer.deployment.containerPort }}
{{- if eq .Values.netdebug "enable"}}
      - name: net-debug
        image: retvari/net-debug:latest
        command: ["/bin/sh"]
        args: ["-c", "while true; do echo hello; sleep 10;done"]
{{- end}}
{{- end}}
---