# lock down access from the TURN server only to kms
---
{{- if eq .Values.mediaServer.deployment.enablement "enable"}}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: "{{ .Values.mediaServer.deployment.name}}-network-policy"
  namespace: default
spec:
  podSelector:
    matchLabels:
      {{- toYaml .Values.mediaServer.deployment.networkPolicy.podSelector | nindent 6 }}
  policyTypes:
  - Egress
  egress:
  - to:
    - podSelector:
        matchLabels:
          {{- include "stunner-kurento-one2one-call.mediaServer.selectorLabels" . | nindent 10 }}
    ports:
    - protocol: UDP
      port: 10000
      endPort: 20000
{{- end}}
---